//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: example.proto
namespace example
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AMessage")]
  public partial class AMessage : global::ProtoBuf.IExtensible
  {
    public AMessage() {}
    
    private int _a;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int a
    {
      get { return _a; }
      set { _a = value; }
    }
    private int _b = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int b
    {
      get { return _b; }
      set { _b = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}